# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180224_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(storage=system.storage.ImageStorage(), upload_to='ad/%Y/%m', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', max_length=200, storage=system.storage.ImageStorage(), upload_to='avatar/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
